"""Resolve EA WRC numeric identifiers using the game-generated catalog."""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any


class WrcCatalogError(ValueError):
    """The game-generated WRC identifier catalog is missing or invalid."""


@dataclass(frozen=True, slots=True)
class WrcCatalog:
    """Versioned lookup tables loaded from EA WRC readme/ids.json."""

    version: dict[str, Any]
    collections: dict[str, dict[int, dict[str, Any]]]

    def lookup(self, collection: str, identifier: object) -> dict[str, Any] | None:
        if isinstance(identifier, bool) or not isinstance(identifier, (int, float)):
            return None
        return self.collections.get(collection, {}).get(int(identifier))


def load_wrc_catalog(path: Path) -> WrcCatalog:
    """Load the read-only catalog regenerated by EA WRC."""

    try:
        data = path.read_bytes()
        encoding = "utf-16" if data.startswith((b"\xff\xfe", b"\xfe\xff")) else "utf-8-sig"
        document = json.loads(data.decode(encoding))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise WrcCatalogError(f"Cannot read WRC identifier catalog {path}: {exc}") from exc
    if not isinstance(document, dict):
        raise WrcCatalogError("WRC identifier catalog root must be an object")

    versions = document.get("versions", {})
    if not isinstance(versions, dict):
        raise WrcCatalogError("WRC identifier catalog versions must be an object")

    collections: dict[str, dict[int, dict[str, Any]]] = {}
    for name in (
        "vehicles",
        "vehicle_classes",
        "vehicle_manufacturers",
        "locations",
        "routes",
        "game_mode",
        "stage_result_status",
    ):
        raw_collection = document.get(name, [])
        if not isinstance(raw_collection, list):
            raise WrcCatalogError(f"WRC identifier collection {name!r} must be a list")
        indexed: dict[int, dict[str, Any]] = {}
        for raw_entry in raw_collection:
            if not isinstance(raw_entry, dict):
                continue
            identifier = raw_entry.get("id")
            if isinstance(identifier, int) and not isinstance(identifier, bool):
                indexed[identifier] = dict(raw_entry)
        collections[name] = indexed
    return WrcCatalog(version=dict(versions), collections=collections)


def enrich_wrc_metadata(metadata: dict[str, Any], catalog: WrcCatalog) -> dict[str, Any]:
    """Add stable human-readable names while retaining every numeric identifier."""

    enriched = dict(metadata)
    mappings = {
        "vehicle": ("vehicles", "vehicle_id"),
        "vehicle_class": ("vehicle_classes", "vehicle_class_id"),
        "vehicle_manufacturer": ("vehicle_manufacturers", "vehicle_manufacturer_id"),
        "location": ("locations", "location_id"),
        "route": ("routes", "route_id"),
        "game_mode_name": ("game_mode", "game_mode"),
        "stage_result_status_name": ("stage_result_status", "stage_result_status"),
    }
    for output_key, (collection, input_key) in mappings.items():
        entry = catalog.lookup(collection, metadata.get(input_key))
        if entry is not None:
            enriched[output_key] = entry.get("name")
    enriched["id_catalog_version"] = catalog.version
    return enriched
